### ISSUE TITLE
Drop `flatten-packages` dependency

### ISSUE THREAD

**Issue by jacobq** [felixrieseberg/electron-windows-store#107]
Removing [this](https://github.com/felixrieseberg/electron-windows-store/blob/e576441e525a4a18ff26d2391ddcba9d55fa39ec/package.json#L38) will help eliminate the annoying warning:
```
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
```

I think that new `npm` flattens automatically, so it should be OK to get rid of this. This will probably also break node 4.x since that doesn't support current `npm`, so it'd be a breaking change.

**Comment by felixrieseberg** [comment]
I'm into this idea though, I think we should go forth and drop it.

**Comment by felixrieseberg** [comment]
And done!
