### ISSUE TITLE
Wrong resolution for icon in taskbar

### ISSUE THREAD

**Issue by baldash** [felixrieseberg/electron-windows-store#125]
I'm trying to set my icons properly but there seems to be 2 issues:

The first one is the icon resolution for the taskbar (weird / bad resolution):

![Electron-Taskbar-Ico](https://user-images.githubusercontent.com/20284898/68109899-028c5900-feec-11e9-99b0-56af0c9984a1.png)

The second one is the icon resolution for the windows store / intaller (too small):

![Electron-Appx-Installer-Ico](https://user-images.githubusercontent.com/20284898/68110035-57c86a80-feec-11e9-8a62-b96e79f2f8bf.png)

[EDIT]

The second one is fixed, I simply had to set another resource than the default selected one in the Appx manifest `<Logo>` section in `<Properties>`

For the other issue I used this comment as a guideline:
https://github.com/electron-userland/electron-builder/issues/987#issuecomment-267406485

My icon quality is better but still the same size

**Comment by baldash** [comment]
Fixed here, sometimes just take a good night of sleep and read more:

https://github.com/electron-userland/electron-builder/issues/987#issuecomment-549735473

**Comment by baldash** [comment]
if someone's interested I created a .bat file to automate the tasks just PM me

**Comment by rugobal** [comment]
Hi, I'm having the exact same problem and I don't know how to fix it. Do you really need to download VS 2015?

Could you please share the .bat file to automate this? It would be a lifesaver.
