### ISSUE TITLE
monitor DPI awareness 

### ISSUE THREAD

**Issue by WeslleyDeSouza** [felixrieseberg/electron-windows-store#129]
Im unable to upload the app to the microsoft store:

High-DPI support

WARNING
DPIAwarenessValidation
Warning: _The DPI-awareness validation test detected following Warnings:
File app\movIT.myMovIT.exe neither has PerMonitorV2 manifested in the manifest nor calls into DPI Awareness APIs for ex: user32!SetProcessDpiAwarenessContext or user32!SetThreadDpiAwarenessContext.
The app movIT.myMovIT_1.1.140.0_x64__8btyn67j2a7a8 is not DPI Aware._

**Impact if not fixed**: Apps that are not DPI-aware but are running on a high-DPI display setting can exhibit incorrect scaling of UI elements, clipped text, and blurry images.

**How to fix**: It is recommended that you declare your app as DPI-aware in the app manifest. Otherwise, app should use DPI Awareness API calls for example:either SetProcessDpiAwarenessContext or SetThreadDpiAwarenessContext APIs.

**Comment by johnxie** [comment]
+1. We are experiencing the same for [Taskade](https://www.taskade.com/downloads/).

**Comment by ronghester** [comment]
+1 we are experiencing the same problem for a brand new desktop app. Wondering is there any easy way to declare the app as DPI-aware in the app manifest ?

**Comment by WeslleyDeSouza** [comment]
should be fixed



> The issue was reported and we got notification that the fix should already be deployed. Please try submitting again and reach out to us if the WACK test still fails with the same error.

Thank you,
Alex
Microsoft Store Team
