### ISSUE TITLE
Taskbar icon is not transparent 

### ISSUE THREAD

**Issue by urvishhingu** [felixrieseberg/electron-windows-store#147]
I build the app using it but the taskbar icon is not transparent. Even after configuring the BackgroundColor="transparent", it is showing background in the taskbar icon and start menu icon.

**Comment by urvishhingu** [comment]
I got a solution using makePri so I am closing this issuue. 

**Reference**
https://github.com/felixrieseberg/electron-windows-store/issues/93

**Comment by urvishhingu** [comment]
I got a solution using makePri so I am closing this issue. 

**Reference**
https://github.com/felixrieseberg/electron-windows-store/issues/93

**Comment by Brouilles** [comment]
@urvish-ajmerainfotech Don't work for me. Maybe need a MinVersion or a specific configuration in the appxmanifest?
