### ISSUE TITLE
Question regarding electron-builder / electron-packager

### ISSUE THREAD

**Issue by black-snow** [felixrieseberg/electron-windows-store#26]
Hi there,

I've recently upgraded my electron app to be built by `electron-builder`. autoUpdate is working w/ Squirrel.

Now I see this package and my first thought is: "Awesome! Just what I was looking for". But on a second read I see that I need to have the outputs from `electron-packager`. Will Windows Store apps have an auto-update built in automagically (via Windows Store)? 
Do I have to drop `electron-builder` / Squirrel when I want to use `electron-windows-store` and move (back) to `electron-packager`?

**Comment by felixrieseberg** [comment]
Hey, thanks for giving it a try!

1) We don't care how you create your `app.exe`, as long as you have one :wink:. `electron-builder` is great, all other alternatives are welcome, too.
2) The Windows Store does indeed have an auto-updater built-in.

**Comment by black-snow** [comment]
Alright, thanks.

**Comment by MarshallOfSound** [comment]
@felixrieseberg So just to clarify when we ship `.appx` files to the Windows Store we should **not** ship them with Squirrel as the Windows Store will handle updates?

**Comment by black-snow** [comment]
@MarshallOfSound that's how I got it, too.
@felixrieseberg Also, what "DRM"-mechenics does the Windows Store provide (for our kind of applications) for paid apps? (Maybe I should make a separate issue for that or not ask this here ...)

**Comment by felixrieseberg** [comment]
@MarshallOfSound: While possible, I'd heavily recommend using the Windows Store for updates if you release via store. It'll handle delta updates for you and probably be more transparent to your users, too.

@black-snow: While there are a bunch of things Windows does to protect your app, we don't guarantee that people won't be able to pirate the appx. If you're asking more generally about "hey, can I sell my app and do in-app purchases, too?" - yes, you totally can :+1:
