### ISSUE TITLE
events.js:141: Unhandled 'error' event

### ISSUE THREAD

**Issue by benoror** [felixrieseberg/electron-windows-store#27]
Hi @felixrieseberg ,

I get the following error while generating the appx, any idea?

Thanks in advance!

```
flatten node_modules complete
Starting Conversion...
Cleaning output folder...
Copying data...
Creating manifest..
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Program Files (x86)\Windows Kits\10\bin\x64\makeappx.exe ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

![capture](https://cloud.githubusercontent.com/assets/119117/16530792/58de8c44-3f8f-11e6-8bfd-2d3e58012eeb.JPG)

**Comment by benoror** [comment]
nvm, I needed to re-install [Windows 10 SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk)

Cheers!

**Comment by black-snow** [comment]
Receiving the same error (but on line 160) with the newest SDK ...
