### ISSUE TITLE
How to communicate between UWP background task and Electron processes

### ISSUE THREAD

**Issue by MarshallOfSound** [felixrieseberg/electron-windows-store#29]
Is their currently a way, or is their a planned way to communicate events and information between Electron and the UWP background task.

I can't see a way to do this currently and the example didn't shine much light on the matter.

Really interested in using this to get access to the `SystemMediaTransportControlsDisplayUpdater` class but that requires sending current song information from Electron to the UWP background task.

**Comment by felixrieseberg** [comment]
Hey! I threw together a quick example for my friends over at Slack, maybe it'll help you too: https://github.com/felixrieseberg/electron-uwp-background

**Comment by bjornlalin** [comment]
Hi. Is there a way to determine if a background task is currently running or not? This is what we are trying to achieve: build the main GUI part of our app in electron but we plan to do some data synchronization in a background task. We want to be able to manually trigger this synchronization from the UI and are looking for the best way to check if it's already running or not, to avoid triggering executing it multiple times in parallel. What would be the best way to be informed about task updates in such a scenario?

**Comment by Praveer1981** [comment]
@MarshallOfSound Did you get the solution . I need to do the same, I referred to 
https://github.com/felixrieseberg/electron-uwp-background
Its not at all working . 
Could you let me know how did you do that ? any sample example ?
