### ISSUE TITLE
UWP packaged app leaves files locked after closing

### ISSUE THREAD

**Issue by MarshallOfSound** [felixrieseberg/electron-windows-store#30]
Not sure if this is somehow an upstream Electron issue that only manifests itself in UWP packaged apps.

Basically I'm packaging my application like so

``` js
  const child = spawn(
    path.resolve(__dirname, 'node_modules', '.bin', 'electron-windows-store.cmd'),
    [
      '--input-directory',
      '"dist\\Google Play Music Desktop Player-win32-ia32"',
      '--output-directory',
      'dist\\uwp',
      '--flatten',
      'true',
      '--package-version',
      '1.0.0.0',
      '--package-name',
      'GPMDP',
      '--package-display-name',
      'Google Play Music Desktop Player',
      '--package-executable',
      'Google Play Music Desktop Player.exe'
    ]
  );

  // spit stdout to screen
  child.stdout.on('data', (data) => process.stdout.write(data));

  // Send stderr to the main console
  child.stderr.on('data', (data) => process.stderr.write(data));

  child.on('close', (code) => {
    done();
  });
```

So pretty standard I think.  When I run the application it launches correctly 🎉 And everything appears to work.

However when I close the application and attempt to run the normal non-UWP win32 version I get a load of "resource locked" errors on the shared files that I create while running the app (Settings and generic Data Storage).

![locked](https://cloud.githubusercontent.com/assets/6634592/17406374/7d5c42c8-5aa6-11e6-9c03-018bd841d85f.PNG)

Is this a limitation of the `appx` magic that is happening because I had to reboot my PC to get those files unlocked which is an absolute nightmare when developing 😢

**Comment by felixrieseberg** [comment]
I assume this is actually not an error inside Electron, but totally with Windows. I hope that Microsoft will get that fixed *before* Project Centennial launches publically.

**Comment by felixrieseberg** [comment]
This should now be fixed in Windows itself, so I'm closing this.
