### ISSUE TITLE
Will appx be accepted into Windows Store?

### ISSUE THREAD

**Issue by BradNewton** [felixrieseberg/electron-windows-store#31]
Will my appx be accepted into the Windows Store?
I've ran the Windows App Certification Kit, it failed with several errors:
	Platform version launch
	App launch
	App prelaunch
	Restricted namespace
	Binary analyzer
	Supported APIs

The minimum version and namespaces have been created automatically.
Binary analyzer and Supported APIs are failing on files that were created by electron-windows-store.
Am I missing some settings?
Or does the WACK just need to be updated to allow electron based apps?

**Comment by felixrieseberg** [comment]
The generated AppX runs fine on any Windows machine with the Anniversary Update, but it is not yet clear when exactly apps will be released to the store.
