### ISSUE TITLE
Signtool fails when using p12 certificate.

### ISSUE THREAD

**Issue by BradNewton** [felixrieseberg/electron-windows-store#32]
We have a certificate with an extension of p12, when I try to use this I get the following error:
SignTool Error: The specified PFX password is not correct.
I've tried adding to the command line: signtool-params "/fd SHA256","/p password"
I've also imported the certificate to the certificate store on my PC.

I am able to sign the file as a separate step using: signtool sign /f path\Cert.p12 /fd SHA256 /p password appname.appx

**Comment by felixrieseberg** [comment]
Hey! Thanks for reporting - this isn't exactly a bug, given that we currently only support PFX signing. However, I'd <3 a PR that extends [this piece of code](https://github.com/felixrieseberg/electron-windows-store/blob/593e7439d0dd313190bdf84cb694be6c037a7633/lib/sign.js#L10-L19) with a quick `if/else` detection to see if the user supplied a p12 (and then to change the arguments).

@BradNewton: Wanna take a crack at it :bow: ?

**Comment by ChrisK2** [comment]
There is another actual bug: signtool only processes parameters up to the filename, everything afterwards is silently ignored. Unfortunately, exactly [this is done](https://github.com/felixrieseberg/electron-windows-store/blob/master/lib/sign.js#L44) with the parameters supplied using the ``--signtool-params`` option, so anything you specifiy there is ignored.

**Comment by felixrieseberg** [comment]
@ChrisK2 Yep, that's a real bug - I'll fix that real quick.

**Comment by felixrieseberg** [comment]
Patched and published!
