### ISSUE TITLE
Is Free Trial on Windows Store supported?

### ISSUE THREAD

**Issue by miloszfalinski** [felixrieseberg/electron-windows-store#33]
I'm in the process of submitting my paid electron app: http://friendlyfox.es/pawsfortrello/ 

I was wondering if you could offer any insight into limitations or possibilities of the Trial option on Windows Store? Is there something that would prevent it from working related to electron?

**Comment by felixrieseberg** [comment]
Yep, that should totally work (in theory). NodeRT should help with calling the respective APIs inside WinRT: https://github.com/NodeRT/NodeRT
