### ISSUE TITLE
Splash screen support

### ISSUE THREAD

**Issue by bostondv** [felixrieseberg/electron-windows-store#35]
Is it possible to support adding a splash screen asset? 

Not sure if it'd just require the asset and manifest changes or if other changes to Electron would be needed, but it'd be nice to have!

**Comment by felixrieseberg** [comment]
That will sadly not work - the splash screen is part of the UWP UI layer and therefore won't work in Electron.

**Comment by bostondv** [comment]
Thanks, too bad... :(
