### ISSUE TITLE
Crash during setup - makecert.exe

### ISSUE THREAD

**Issue by black-snow** [felixrieseberg/electron-windows-store#37]
> Please enter the location of your Windows Kit's bin folder:
> C:\Program Files (x86)\Windows Kits\10\bin\x86
> Creating Certificate
> When asked to enter a password, please select "None".
> events.js:160
>    throw er; // Unhandled 'error' event
> 
> Error: spawn C:\Program Files (x86)\Windows Kits\10\bin\x86 ENOENT
>  at exports._errnoException (util.js:1007:11)
>  ...

Win 10 Pro @32bit, Version 1511 (Build 10586.589)
node v6.2.1
Windows SDK 10.1.10586.212

**Comment by jacobq** [comment]
I'm not sure if you're still having this problem, but you might want to check out the work done [on `electron-forge` here](https://github.com/electron-userland/electron-forge/blob/master/src/makers/win32/appx.js#L8-L30). You should also check that the Windows 10 SDK is installed.

**Comment by black-snow** [comment]
@jacobq Thanks. Dunno if this is actually still a valid issue - gonna close it for now.

**Comment by nlappas** [comment]
Same issue. It stems from the fact that the `makecert.exe` cannot be found in the recommended directory.

Maybe update the instructions to reflect the fact that `makecert.exe` resides in `C:\Program Files (x86)\Windows Kits\10\bin\<Windows 10 SDK version number>\x64` ?

**Comment by black-snow** [comment]
That's only true if you didn't install it anywhere else ;)
For me it's E:\WindosSDK\
Anyhow, it sure should be mentioned that the sdk binaries must be in the path.
