### ISSUE TITLE
Fails executing *.ps1 script - restricted

### ISSUE THREAD

**Issue by black-snow** [felixrieseberg/electron-windows-store#39]
> Please enter your app's package name (name of your exe):
> Please enter your app's package version:
> Flattening modules...
> & : Die Datei "...\ps1\flattennpmmodules.ps1" kann nicht geladen werden, da die Ausführung von Skripts auf diesem System deaktiviert ist. Weitere Informationen finden Sie unter "about_Execution_Policies" (http://go.microsoft.com/fwlink/?LinkID=135170).
> In Zeile:1 Zeichen:6
> + & {& '...
> + CategoryInfo : Sicherheitsfehler: (:) [], PSSEcurityException
> + FullyQualifiedErrorId : UnauthorizedAccess
> ...
> events.js:160
>     throw er; // Unhandled 'error' event
>
> Error: spawn ...\makeappx.exe ENOENT
> ...

Runnin `Get-ExecutionPolicy` in the PowerShell returns `Restricted`. Gonna change that and see what happens but this should probably go into the README / wiki. (This seems to be the default setting)

**Comment by black-snow** [comment]
Error goes away after running `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned` from an elevated PowerShell.

**Comment by felixrieseberg** [comment]
Added to the readme, thanks!
