### ISSUE TITLE
Shipping 3rd party installers

### ISSUE THREAD

**Issue by black-snow** [felixrieseberg/electron-windows-store#41]
Hey there,

currently I'm shipping a 3rd party installer with my application. It's run during setup. Do you see any way to include that installer when packing for the windows store?

My best idea right now is to somehow ship the installer (msi/exe) and explicitly run it on first app launch.

**Comment by felixrieseberg** [comment]
The Windows Store is your new installer :wink:. You can just package up the final result - for that, you might want to run your installer inside the fully virtualized conversion, which takes your MSI and turns it into a package. You won't need `electron-windows-store` for that, but I'd rather recommend the best tool for the job.

For more information, check this out: https://msdn.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-run-desktop-app-converter

**Comment by black-snow** [comment]
Sadly I'm tied to a 32bit version of windows 10 - *afaik* the converter requires a 64bit version.

The machine has a 64bit chip, though. Do you know if I can run the converter inside an unregistered 64bit virtual machine win10? An uglay workaround but this might work. @felixrieseberg

**Comment by felixrieseberg** [comment]
I'm actually not sure (32 hosting 64 vm sounds scary), but it's worth a try?
