### ISSUE TITLE
Support hardware/software not clear

### ISSUE THREAD

**Issue by patricksebastien** [felixrieseberg/electron-windows-store#47]
I was looking at the documentation:
https://github.com/electron/electron/blob/master/docs/tutorial/windows-store-guide.md

It's not clear to me what it is supported. When uploading an electron-windows-store .appx users will be able to use my app on:

- Windows 10 (PC)
- Windows 8 (PC) ?
- Windows Tablet ?

From the doc: it will not runs on:
- Xbox
- HoloLens
- Phones ?!

Why not on Phones? If I need to support this I will need to use something like cordova?
Thanks

**Comment by felixrieseberg** [comment]
I added this to the readme - you're still running a `win32` binary, which will only run on win32 devices. So no, sadly no support for anything but good ol' Windows :wink:
