### ISSUE TITLE
Support for Manifest uap:SplashScreen

### ISSUE THREAD

**Issue by jimpdx** [felixrieseberg/electron-windows-store#53]
Would it be possible to incorporate support for the <uap:SplashScreen> element in the manifest XML file?
https://msdn.microsoft.com/en-us/library/windows/apps/dn934810.aspx

**Comment by felixrieseberg** [comment]
Hey, thanks for giving this a spin! If you're running Electron, you're not running a UWP app. There's no app that'd be able to display said splash screen :wink:

**Comment by jimpdx** [comment]
Ah ha, good to know :) Thanks Felix. I am still learning this whole electron/windows stuff after years of iOS/Xcode/Cordova. Cheers.
