### ISSUE TITLE
Question: Is the resulting App compatible with Assigned Access?

### ISSUE THREAD

**Issue by conteit** [felixrieseberg/electron-windows-store#54]
I'd like to run an electron application packaged as AppX with Assigned Access.

Is it possible?

**Comment by felixrieseberg** [comment]
Should be.

**Comment by conteit** [comment]
I've tried.

Unfortunately it is not able to start (I see the splash screen flashing) then windows gives error 0x80270254.

Any idea? Thank you

**Comment by Phillips126** [comment]
I'm also not able to get the application to work with Assigned Access.  When the user logs in, Windows attempts to run the application (blue window appears with the loading spinner).  The whole screen flickers for a minute or so and then an error message appears stating:

_**"We weren't able to start your app.  Press Ctrl + Alt + Del to sign out or contact your system admin.  For more info, search online for error code: 0x80270254".**_

Searching this error code seems to yield no solution.

To rule out my application code (as it has a lot going on), I created a simple "Hello World" application and that also experiences the same problem.

Any thoughts?  Thanks!

**Comment by felixrieseberg** [comment]
I have to admit that I know little about Assigned Access - if it actually doesn't work, it probably has little to do with Electron and more with how Microsoft set Assigned Access up.

Might be a good idea to let the dev team know - maybe this is an easy fix (https://wpdev.uservoice.com/forums/110705-universal-windows-platform/category/161895-desktop-bridge-centennial)

**Comment by Phillips126** [comment]
Thanks @felixrieseberg, I'll devote a little time to look into this further.
I was really just experimenting with some in-house applications and really enjoy using Electron.

If I find anything further I'll update this post.

**Comment by conteit** [comment]
I opened this topic on the site @felixrieseberg suggested: https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/17450752-assigned-access-not-working-with-electron

I hope I provided them with all informations. Maybe @Phillips126, you can integrate it and vote it up.

**Comment by felixrieseberg** [comment]
Well done, let's hope we'll get somewhere!

**Comment by felixrieseberg** [comment]
(I'll also bring it up with the Electron Maintainers)

**Comment by tvanro** [comment]
Like @conteit is saying, it is probably because of Windows.FullTrustApplication:
http://stackoverflow.com/questions/41047093/how-to-launch-a-win32-application-to-run-like-a-windows-10-assigned-access-appx
