### ISSUE TITLE
Trying to add icon with no success

### ISSUE THREAD

**Issue by AhadCove** [felixrieseberg/electron-windows-store#60]
im using --icon=src/assets/icons/win/icon.ico with no success For some reason the icon is just not changing.
Am I doing something wrong?

**Comment by felixrieseberg** [comment]
Are you in the right repo? We don't even have an `icon` option 😆. `electron-windows-store` isn't responsible for the icon of your Electron app, you'd do that with `electron-packager` or any of the other "compilation" packages :wink:

**Comment by AhadCove** [comment]
Oh okay, didn't know lol. That makes sense. Yes im in the right repo just didn't realize I had to set that in electron-packager hahaha
