### ISSUE TITLE
Manifest Restricted Capabilites Error

### ISSUE THREAD

**Issue by AhadCove** [felixrieseberg/electron-windows-store#61]
When trying to upload my appx to the app store I am running into this error. The link no longer exists, so I don't exactly know how to fix it

Package acceptance validation error: You don't have permissions to specify the following namespaces in the appx manifest file of the package App.appx: http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities

**Comment by felixrieseberg** [comment]
Please read the `readme`:

> ⚠️ If you want to submit your package to the Windows Store, please sign up for the Desktop Bridge Program. Microsoft will currently not accept your packages if you have not done so.
