### ISSUE TITLE
DPI settings not honored, window is blurry from scaling, not crisp like desktop electron or Chrome.

### ISSUE THREAD

**Issue by AaronFriel** [felixrieseberg/electron-windows-store#62]
I'm creating this issue primarily as a tracking issue because I use Slack and I opened it up to find it was very blurry on Windows 10. It's unusably bad on a Surface Pro 3 at 150% scaling. Or at least, to my preferences, I'll uninstall and stick with the web app. Below you can see the Slack UWP app and the same text in Edge.

![image](https://cloud.githubusercontent.com/assets/788800/22081884/0b1c18e2-dd8b-11e6-9cff-d898c38fce64.png)

This is an aside for @felixrieseberg, but what are the technical merits of embedding Electron versus using a web application packaged for UWP?

**Comment by goodhyun** [comment]
Did you try to reboot Windows 10 ? We also experienced that mismatch when we were tinkering with dpi, but now we can see a clear screen.

**Comment by stealer0517** [comment]
I have the exact same issue, except I haven't been playing with my DPI settings. 
It happens when I open my laptops screen when on the dock.
All of my displays run at 100% scaling, but windows originally wanted my laptops screen to run at 125% so that may be part of the issue.

**Comment by uranusjr** [comment]
This seems to happen when you have screens using difference DPI settings. My notebook uses 200% scaling by default, and Slakc works correctly on the default display, but start having the mentioned issues when I move it to my external display with 100% scaling.

I would also like to note that there are scaling issues with system UI elements as well, including gigantic menu when you right-click on the menu bar, and input method popovers.

![1](https://user-images.githubusercontent.com/605277/36661592-a2f1e8a8-1b16-11e8-9b2d-1026ffb9f0e4.png)
![2](https://user-images.githubusercontent.com/605277/36661595-a5b11a32-1b16-11e8-80fc-02f8881c4fa1.png)
