### ISSUE TITLE
Assets scale not being recognized

### ISSUE THREAD

**Issue by AhadCove** [felixrieseberg/electron-windows-store#63]
I am trying to add my custom assets folder to add icons to my appx installer. For some reason it is not recognizing that these are the icons I want to use and is defaulting to the samples.
My folder does copy to the correct place and all of my icons are

```
Logo.scale-44.png
Logo.scale-50.png
Logo.scale-150.png
Logo.scale-310.png
```

And my config is:
```
        "assets": "./build/appxAssets/"

```
But, the appx still defaults to the samples instead

**Comment by stefanhuber** [comment]
Is this working?

**Comment by AhadCove** [comment]
For some reason the manifest still doesnt pick up my assets folder. They continue to use the default samples

**Comment by stefanhuber** [comment]
Inside the template for the manifest the respective values are hardcoded... So one has to use the same names.

https://github.com/felixrieseberg/electron-windows-store/blob/master/template/appxmanifest.xml

**Comment by AhadCove** [comment]
Ohhh I see

**Comment by AhadCove** [comment]
Trying it out now

**Comment by felixrieseberg** [comment]
One could just overwrite the manifest - this module supports that already.
