### ISSUE TITLE
How to make appx a "Silent" installer

### ISSUE THREAD

**Issue by AhadCove** [felixrieseberg/electron-windows-store#64]
I am currently in contact with windows desktop bridge consultant trying to get my app in the store. I am using electron-forge that is using electron-windows-store for appx and the consultant is telling me that the install needs to be silent and he is running into problems with his review tool because it's not
Any one have any idea what he means or how I could make it "silent"

**Comment by felixrieseberg** [comment]
Since Slack is in the store and uses this package, I'm afraid you'll have to work through this with your consultant...
