### ISSUE TITLE
[Question] How to remove electron userData folder when uninstalling

### ISSUE THREAD

**Issue by jacobq** [felixrieseberg/electron-windows-store#75]
I'm using [`electron-settings`](https://github.com/nathanbuchar/electron-settings) and [`ember-localstorage-adapter`](https://github.com/locks/ember-localstorage-adapter) in my application, which results in data being saved to `C:\Users\User\AppData\Roaming\myapp`. However, this folder persists after uninstallation. Is there a way to configure `electron-windows-installer` to remove it (possibly prompting the user for confirmation) when uninstalling?

**Comment by jacobq** [comment]
See also https://github.com/electron/windows-installer/issues/113

**Comment by wuharvey** [comment]
Bumping this.
