### ISSUE TITLE
How to use Desktop App Converter

### ISSUE THREAD

**Issue by clusterberries** [felixrieseberg/electron-windows-store#78]
Hi all! 
I want to use Desktop App Converter, but the link in README is not valid (https://www.microsoft.com/en-us/download/details.aspx?id=51691). Converter is available in Win Store, but I don't understand how to use the application with electron-windows-store, because it requires path to *.ps1 file.

**Comment by Joshua-Smith** [comment]
Did you ever figure this out? I'm hitting the same issue. It appears DAC used to be a script and now it's an exe.

**Comment by clusterberries** [comment]
@Joshua-Smith I installed DAC from the Store, followed the instructions and was able to create *.appx file. But I still don't know how to user it together with electron-windows-store.

**Comment by Joshua-Smith** [comment]
I found that electron-windows-store is really not necessary, nor does this DAC thing seem to be. I got EWS to generate a manifest that I could use as a starting point, and now I'm just running makeappx.exe directly.

**Comment by felixrieseberg** [comment]
Sorry that I wasn't more active here, Microsoft moved the README to https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-run-desktop-app-converter.
