### ISSUE TITLE
pre-appx\AppXManifest.xml is wrong

### ISSUE THREAD

**Issue by Wenish** [felixrieseberg/electron-windows-store#99]
Im getting an error when im creating the win store package

win-unpacked is ths built electron app
target is the win-store folder
both is on my desktop

Im running this with Windows PowerShell as Admin

```ps
C:\Users\jonas\Desktop> electron-windows-store --input-directory win-unpacked --output-directory win-store --flatten
true --package-version 1.0.0.0

Configuration:
Desktop Converter Location:    false
Expanded Base Image:           false
Publisher:                     CN=developmentca
Dev Certificate:               C:\Users\jonas\AppData\Roaming\electron-windows-store\developmentca\developmentca.pfx
Windows Kit Location:          C:\Program Files (x86)\Windows Kits\10\bin\x64

? Please enter your app's package name (name of your exe - without '.exe'):  somePackageName
Flattening modules...
Starting Conversion...
Cleaning pre-appx output folder...
Copying data...
Creating manifest..
Creating appx package...
Microsoft (R) MakeAppx Tool
Copyright (C) 2013 Microsoft.  All rights reserved.

The path (/p) parameter is: "win-store\somePackageName.appx"
The content directory (/d) parameter is: "win-store\pre-appx"
Enumerating files from directory "win-store\pre-appx"
Packing 123 file(s) in "win-store\pre-appx" (content directory) to "win-store\somePackageName.appx" (output file name).
Using "win-store\pre-appx\AppXManifest.xml" as the manifest for the package.
MakeAppx : error: Manifest validation error: Line 26, Column 39, Reason: The file name "app\somePackageName.exe" declared for element "*[local-name()='Applications']/*[local-name()='Application']" doesn't exist in the package.
MakeAppx : error: Package creation failed.
MakeAppx : error: 0x80080204 - The specified package format is not valid: The package manifest is not valid.

Error: C:\Program Files (x86)\Windows Kits\10\bin\x64\makeappx.exe exited with code: 1
    at ChildProcess.child.on (C:\Users\jonas\AppData\Roaming\npm\node_modules\electron-windows-store\lib\utils.js:74:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
Error: C:\Program Files (x86)\Windows Kits\10\bin\x64\makeappx.exe exited with code: 1
    at ChildProcess.child.on (C:\Users\jonas\AppData\Roaming\npm\node_modules\electron-windows-store\lib\utils.js:74:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

those are my folders:
https://drive.google.com/open?id=1xSQDKYoZWxHBvZmW50cP6ld8KiRwLf44

**Comment by arnoldsandoval** [comment]
I too am running in to this issue, @Wenish have you found any resolution?

**Comment by bishbashbosh123** [comment]
I had this too. This is the error:
>MakeAppx : error: Manifest validation error: Line 26, Column 39, Reason: The file name "app\somePackageName.exe" declared for element "*[local-name()='Applications']/*[local-name()='Application']" doesn't exist in the package.
If you look in the "win-store\pre-appx\AppXManifest.xml line 26 you can see `Executable="app\somePackageName.exe"` but that .exe doesn't exist in your app/ directory.

> Please enter your app's package name (name of your exe - without '.exe'):  somePackageName
This has to match the name of your .exe in your win-unpacked directory. So... mem-launcher in your case I think.

**Comment by phillee** [comment]
In case you haven't solved this, you can fix it by specifying the .exe name with package-executable

**Comment by LotuxPunk** [comment]
Hi ! I have the same issue. How can I generate the .exe required ?

**Comment by Excigma** [comment]
I ran into the same problem and solved it by adding --package-executable app/<your exe name>.exe
Go to the pre/appx folder (even it has failed) and find the name of the exe from there

**Comment by alphabiz-se4** [comment]
If the Executable file exists and the path is correct, check that the folder is a shortcut. 
If folders are shortcuts, `The file name "alphabiz.exe" declared for element "*[local-name()='Applications']/*[local-name()='Application']" Doesn't exist in the package.` This error occurs. I've been obsessing over this all day.
![image](https://user-images.githubusercontent.com/92558550/167233434-fe9419d1-7ea2-499a-9197-9198d27fafbf.png)
